server:
  port: 8090
  servlet:
    context-path: /template/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: dev
    password: devpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      use-new-ID-generator-mappings: true
      ddl-auto: create
    open-in-view: false
